version: 2

sources:
  - name: hp
    tables:
      - name: raw_linhas
        description: "Tabela contendo todos os dados descritivos das linhas"
      - name: raw_trajetos
        description: "Tabela contendo os dados de geolocalização das linhas, fazendo referência a tabela raw_linhas"
      - name: raw_escalas_programadas
        description: "Tabela contendo informações originadas das papeletas, com informações de carro, motorista e linha, todas programadas"
      - name: raw_geodata
        description: "Dados de geolocalização que tem origem na Mix Telematics."

