services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: adminpoc
      POSTGRES_PASSWORD: adminpoc
      POSTGRES_DB: poc-db
    ports:
      - "5440:5432"
    volumes:
      - my-db:/var/lib/postgresql/data

volumes:
  my-db:
